### ISSUE TITLE
Need to convert from XHTML to HTML5 format for all HTML docs

### ISSUE THREAD

**Issue by Mr-Kumar-Abhishek** [arijitlaik/arijitlaik.github.io#1]
The web pages follow XHTML format, this needs to be converted to HTML5. (for better searches from their semantics).

**Comment by arijitlaik** [comment]
this repo is a basic page personal and has no real use/purpose, a properly maintained HTML5 page would be created as and when is necessary

**Comment by arijitlaik** [comment]
vague issue closed

**Comment by Mr-Kumar-Abhishek** [comment]
Vague ? Currently HTML 5 are required for good searches from search engines. As your website is pretty new it is advised to use HTML 5 for your portfolio( website). It will provide good SEO (search engine optimization) for it. No one will benefit from old XHTML. Make internet better by using HTML5. Using tags such as `<nav>` `<header>` and `<footer>` tags will provide good semantics, and good searches for search engines. I didn't thought I had to tell such trivials about this issue.

**Comment by arijitlaik** [comment]
### well do check out the semantics on my other repos https://github.com/arijitlaik?tab=repositories and the sub dirs on this repo and , fyi i am primarily a science postgraduate, i barely need a portfolio website :) , other repos have proper tags metadata and semantics which serve their purpose, this one was just an good-old gh-pages test

**Comment by Mr-Kumar-Abhishek** [comment]
#At least provide a good readme for the purpose of this repo , people get confused. I suppose as this is hosted, it is a proper project ?

**Comment by arijitlaik** [comment]
well i am a hobbist, will do when i have spare time or time off from my 
masters thesis,   this isnt a proper project, some sub dirs like 
https://github.com/arijitlaik/arijitlaik.github.io/tree/master/puscicgpa
https://github.com/arijitlaik/arijitlaik.github.io/tree/master/pi2pl
were small hosted apps,
when i find time i code this repo
https://github.com/arijitlaik/SvgNet
which is a html5/JS implementation of some scientific structural 
geology plots
